# Generated by Django 2.2 on 2019-06-20 09:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/grean/image/upload/v1560445304/default_ddfimn.png', max_length=255, verbose_name='image'),
        ),
    ]
