# Generated by Django 2.2 on 2019-05-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190507_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
