# Generated by Django 2.2 on 2019-05-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190516_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bookmarksCount',
        ),
    ]
