# Generated by Django 2.2 on 2019-05-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
        ('articles', '0002_auto_20190510_0825'),
    ]

    operations = [
    ]
